name: Podman CI Ubuntu

on:
  push:
    branches: [ main ]
    paths-ignore: [ docs/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-earthly-docker:
    uses: ./.github/workflows/build-earthly.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      # TODO: figure out why --push is failing with podman auth. For now we push the original binary
      # with docker for use in future tests.
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  build-earthly-podman:
    uses: ./.github/workflows/build-earthly.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      # TODO: this does not push the binary we build because pushing with podman is failing. We need
      # to figure out why and fix it so we can use the binary from this job for future tests.
      BINARY: "podman"
      SUDO: "sudo -E"
    secrets: inherit

  podman-lint:
    needs: build-earthly-docker
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+lint-all"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo -E"
    secrets: inherit

  podman-tests-no-qemu:
    needs: build-earthly-docker
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo -E"
    secrets: inherit

  podman-tests-require-account-access:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    needs: build-earthly-docker
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "./tests+tests-that-require-earthly-technologies-account-access"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo -E"
    secrets: inherit

  podman-tests-qemu:
    needs: build-earthly-docker
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-qemu"
      USE_QEMU: true
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo -E"
    secrets: inherit

  podman-examples-1:
    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
    needs:
    - build-earthly-docker
    uses: ./.github/workflows/reusable-example.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo -E"
      EXAMPLE_NAME: "+examples1"
    secrets: inherit

  podman-examples-2:
    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
    needs:
    - build-earthly-docker
    uses: ./.github/workflows/reusable-example.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo -E"
      EXAMPLE_NAME: "+examples2"
    secrets: inherit

#  podman-test-local:
#    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
#    needs:
#    - build-earthly-docker
#    uses: ./.github/workflows/reusable-test-local.yml
#    with:
#      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
#      RUNS_ON: "ubuntu-latest"
#      BINARY: "podman"
#      BINARY_COMPOSE: "\"sudo -E podman-compose\""
#      SUDO: "sudo -E"
#    secrets: inherit
#
# TODO: Fix and bring back the below tests
#  podman-push-integrations:
#    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
#    needs: build-earthly-docker
#    uses: ./.github/workflows/reusable-push-integrations.yml
#    with:
#      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
#      RUNS_ON: "ubuntu-latest"
#      BINARY: "podman"
#      SUDO: "sudo -E"
#    secrets: inherit
#
#  podman-secret-integrations:
#    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
#    needs:
#    - build-earthly-docker
#    uses: ./.github/workflows/reusable-secrets-integrations.yml
#    with:
#      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
#      RUNS_ON: "ubuntu-latest"
#      BINARY: "podman"
#      SUDO: "sudo -E"
#    secrets: inherit
#
#  podman-bootstrap-integrations:
#    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
#    needs:
#    - build-earthly-docker
#    uses: ./.github/workflows/reusable-bootstrap-integrations.yml
#    with:
#      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
#      RUNS_ON: "ubuntu-latest"
#      BINARY: "podman"
#      SUDO: "sudo -E"
#    secrets: inherit
#
#  podman-repo-auth-tests:
#    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
#    needs:
#    - build-earthly-docker
#    uses: ./.github/workflows/reusable-repo-auth-tests.yml
#    with:
#      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
#      RUNS_ON: "ubuntu-latest"
#      BINARY: "podman"
#      SUDO: "sudo -E"
#    secrets: inherit
#
#  podman-export-tests:
#    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
#    needs:
#    - build-earthly-docker
#    uses: ./.github/workflows/reusable-export-test.yml
#    with:
#      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
#      RUNS_ON: "ubuntu-latest"
#      BINARY: "podman"
#      SUDO: "sudo -E"
#    secrets: inherit
#
#  podman-misc-tests:
#    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
#    needs:
#    - build-earthly-docker
#    uses: ./.github/workflows/reusable-misc-tests.yml
#    with:
#      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
#      RUNS_ON: "ubuntu-latest"
#      BINARY: "podman"
#      SUDO: "sudo -E"
#    secrets: inherit
